kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-redis-app-0
  labels:
    app: redis
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mb
  selector:
    matchLabels:
      path: nfsshare1
      app: redis
      podindex: "0"
