kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-redis-app-2
  labels:
    app: redis
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200M
  selector:
    matchLabels:
      path: nfsshare3
      app: redis
      podindex: "2"
