---
apiVersion: v1
kind: Service
metadata:
  name: arangodb-agents
spec:
  ports:
    - port: 8529
      targetPort: 8529
  clusterIP: None
  selector:
    name: arangodb
    role: agent
---
apiVersion: v1
kind: Service
metadata:
  name: arangodb-coords
spec:
  ports:
    - port: 8529
      targetPort: 8529
  type: LoadBalancer
  selector:
    name: arangodb
    role: coordinator
---
apiVersion: v1
kind: Service
metadata:
  name: arangodb-dbs
spec:
  ports:
    - port: 8529
      targetPort: 8529
  type: LoadBalancer
  selector:
    name: arangodb
    role: dbserver
